---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: virtlet
  namespace: kube-system

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: test
spec:
  containers:
  - image: docker.io/busybox
    name: tst
    resources: {}
status: {}

