---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    virtlet.cloud: ""
  name: virtletimagemappings.virtlet.k8s
spec:
  group: virtlet.k8s
  names:
    kind: VirtletImageMapping
    plural: virtletimagemappings
    shortNames:
    - vim
    singular: virtletimagemapping
  scope: Namespaced
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    virtlet.cloud: ""
  name: virtletconfigmappings.virtlet.k8s
spec:
  group: virtlet.k8s
  names:
    kind: VirtletConfigMapping
    plural: virtletconfigmappings
    shortNames:
    - vcm
    singular: virtletconfigmapping
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            config:
              properties:
                calicoSubnetSize:
                  maximum: 32
                  minimum: 0
                  type: integer
                cniConfigDir:
                  type: string
                cniPluginDir:
                  type: string
                cpuModel:
                  type: string
                criSocketPath:
                  type: string
                databasePath:
                  type: string
                disableKVM:
                  type: boolean
                disableLogging:
                  type: boolean
                downloadProtocol:
                  pattern: ^https?$
                  type: string
                enableRegexpImageTranslation:
                  type: boolean
                enableSriov:
                  type: boolean
                fdServerSocketPath:
                  type: string
                imageDir:
                  type: string
                imageTranslationConfigsDir:
                  type: string
                libvirtURI:
                  type: string
                logLevel:
                  maximum: 2147483647
                  minimum: 0
                  type: integer
                rawDevices:
                  type: string
                skipImageTranslation:
                  type: boolean
            nodeName:
              type: string
            nodeSelector:
              type: object
            priority:
              type: integer
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null

