#!/usr/bin/expect -f
set timeout 600
set domain [lindex $argv 0]

spawn virsh -c qemu+tcp://virtlet/system console $domain

expect {
    timeout { puts "initial message timeout"; exit 1 }
    "Escape character"
}
send "\r"

expect {
    timeout { puts "login prompt timeout"; exit 1 }
    "login:"
}
send "cirros\r"

set timeout 20
expect {
    timeout { puts "password prompt timeout"; exit 1 }
    "Password: "
}
sleep 3
send "cubswin:)\r"

expect {
    timeout { puts "shell prompt timeout"; exit 1 }
    -re "\n\\$"
}
send "/sbin/ifconfig\r"

expect {
    timeout { puts "shell prompt timeout"; exit 1 }
    -re "\n\\$"
}
send "exit\r"

expect {
    timeout { puts "login prompt timeout"; exit 1 }
    "login:"
}
