apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - /usr/local/bin/kube-apiserver $APISERVER_OPTS
    image: gcr.io/google_containers/kube-apiserver
    imagePullPolicy: IfNotPresent
    name: kube-apiserver
    ports:
    - {containerPort: 443, hostPort: 443, name: https, protocol: TCP}
    - {containerPort: 8080, hostPort: 8080, name: local, protocol: TCP}
  dnsPolicy: ClusterFirst
  hostNetwork: true
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
