apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - /usr/local/bin/kube-controller-manager $CONTROLLER_OPTS
    image: gcr.io/google_containers/kube-controller-manager
    imagePullPolicy: IfNotPresent
    name: kube-controller-manager
  dnsPolicy: ClusterFirst
  hostNetwork: true
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
