apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - /usr/local/bin/kube-scheduler $SCHEDULER_OPTS
    image: gcr.io/google_containers/kube-scheduler
    imagePullPolicy: IfNotPresent
    name: kube-scheduler
  dnsPolicy: ClusterFirst
  hostNetwork: true
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
