version: "2"
checks:
  argument-count:
    config:
      threshold: 8
  complex-logic:
    config:
      threshold: 8
  file-lines:
    config:
      threshold: 1024
  method-complexity:
    config:
      threshold: 100
  method-count:
    config:
      # CRI runtime implementation has >20 methods
      threshold: 25
  method-lines:
    config:
      threshold: 200
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 8
  similar-code:
    enabled: false
  identical-code:
    enabled: false
plugins:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
ratings:
  paths:
    - "**.go"
exclude_patterns:
  - "vendor/"
  - "pkg/diskimage/guestfs/guestfs.go"
  - "tests/"
  - "**/*_test.go"
  - "*_test.go"
  - "pkg/tools/bindata.go"
  # the fields and consts there are named after corresponding
  # CRI fields / consts, but make CodeClimate unhappy due to
  # underscores and "Id" instead of "ID"
  - "pkg/metadata/types/types.go"
  # gofmt issue in the generated code
  - "pkg/client/clientset/versioned/clientset.go"
