version: "2"
checks:
  argument-count:
    config:
      threshold: 8
  complex-logic:
    config:
      threshold: 8
  file-lines:
    config:
      threshold: 1024
  method-complexity:
    config:
      threshold: 100
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 200
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 8
plugins:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
ratings:
  paths:
    - "**.go"
exclude_patterns:
  - "vendor/"
  - "pkg/diskimage/guestfs/guestfs.go"
  - "tests/"
  - "**/*_test.go"
  - "*_test.go"
