#!/usr/bin/expect -f
# Copyright 2017 Mirantis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

proc connect_ssh {vmname} {
    set t 10
	set i $t
	while {[attempt_connect_ssh $vmname]} { 
		sleep 1
		set i [expr $i - 1]
		if {$i <= 0} {
			puts "Timed out retrying to ssh to ${vmname}"
	     	exit 1
		}
		puts "Retry ssh to $vmname ([expr $t - $i]/${t})" 
	}
}

proc attempt_connect_ssh {vmname} {
    global spawn_id
    spawn ../../examples/vmssh.sh "cirros@${vmname}"
    expect {
        "Warning: Permanently added '${vmname}.default' (RSA) to the list of known hosts." {
            return 0
        }
        "ssh_exchange_identification: Connection closed by remote host" {
            return 1 
        }
    }
    return 1
}
