#!/usr/bin/expect -f
# Copyright 2017 Mirantis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set timeout 600
set domain [lindex $argv 0]

spawn ../../examples/virsh.sh console $domain

expect {
    timeout { puts "initial message timeout"; exit 1 }
    "Escape character"
}
send "\r"

expect {
    timeout { puts "login prompt timeout"; exit 1 }
    "login:"
}
send "cirros\r"

set timeout 20
expect {
    timeout { puts "password prompt timeout"; exit 1 }
    "Password: "
}
sleep 3
send "letmein\r"

expect {
    timeout { puts "shell prompt timeout"; exit 1 }
    -re "\n\\$"
}
send "/sbin/ifconfig\r"

expect {
    timeout { puts "shell prompt timeout"; exit 1 }
    -re "\n\\$"
}
send "exit\r"

expect {
    timeout { puts "login prompt timeout"; exit 1 }
    "login:"
}
