#!/usr/bin/expect -f
# Copyright 2017 Mirantis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set timeout 600
set vmname [lindex $argv 0]

source ./common.exp

connect_ssh $vmname

# display network config for the purpose of diagnostics
expect {
    timeout { puts "shell prompt timeout"; exit 1 }
    -re "\n\\$"
}
send "ip a\r"

expect {
    timeout { puts "shell prompt timeout"; exit 1 }
    -re "\n\\$"
}
send "ip r\r"

expect {
    timeout { puts "shell prompt timeout"; exit 1 }
    -re "\n\\$"
}
send "ping -c1 8.8.8.8\r"

expect {
    timeout { puts "timed out waiting for proper ping response"; exit 1 }
    "1 packets transmitted, 1 packets received, 0% packet loss"
}

expect {
    timeout { puts "shell prompt timeout"; exit 1 }
    -re "\n\\$"
}
send "curl http://nginx.default.svc.cluster.local\r"

expect {
    timeout { puts "timed out waiting for nginx response"; exit 1 }
    "Thank you for using nginx."
}

expect {
    timeout { puts "shell prompt timeout"; exit 1 }
    -re "\n\\$"
}
send "exit\r"

expect {
    timeout { puts "login prompt timeout"; exit 1 }
    "Connection to ${vmname}.default closed."
}
