apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: image-server
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: image-server
      annotations:
        pod.beta.kubernetes.io/init-containers: >
          [
            {
              "name": "dl-image",
              "image": "alpine:3.5",
              "imagePullPolicy": "IfNotPresent",
              "command": ["/bin/sh", "-c", "apk update && apk add ca-certificates wget && wget -O /images/cirros https://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img && touch /images/ready"],
              "volumeMounts": [
                {
                  "name": "images",
                  "mountPath": "/images"
                }
              ]
            }
          ]
    spec:
      containers:
      - name: web
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 2
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: images
      volumes:
      - name: images
        emptyDir: {}
