calicoSubnetSize: 22
cniConfigDir: /some/cni/conf/dir
cniPluginDir: /some/cni/bin/dir
cpuModel: host-model
criSocketPath: /some/cri.sock
databasePath: /some/file.db
disableKVM: true
disableLogging: true
downloadProtocol: http
enableRegexpImageTranslation: false
enableSriov: true
fdServerSocketPath: /some/fd/server.sock
imageDir: /some/image/dir
imageTranslationConfigsDir: /some/translation/dir
kubeletRootDir: /var/lib/kubelet/pods
libvirtURI: qemu:///foobar
logLevel: 1
rawDevices: sd*
skipImageTranslation: false
streamPort: 10010
