/*
Copyright 2018 Mirantis

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	virtlet_k8s_v1 "github.com/Mirantis/virtlet/pkg/api/virtlet.k8s/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVirtletImageMappings implements VirtletImageMappingInterface
type FakeVirtletImageMappings struct {
	Fake *FakeVirtletV1
	ns   string
}

var virtletimagemappingsResource = schema.GroupVersionResource{Group: "virtlet.k8s", Version: "v1", Resource: "virtletimagemappings"}

var virtletimagemappingsKind = schema.GroupVersionKind{Group: "virtlet.k8s", Version: "v1", Kind: "VirtletImageMapping"}

// Get takes name of the virtletImageMapping, and returns the corresponding virtletImageMapping object, and an error if there is any.
func (c *FakeVirtletImageMappings) Get(name string, options v1.GetOptions) (result *virtlet_k8s_v1.VirtletImageMapping, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(virtletimagemappingsResource, c.ns, name), &virtlet_k8s_v1.VirtletImageMapping{})

	if obj == nil {
		return nil, err
	}
	return obj.(*virtlet_k8s_v1.VirtletImageMapping), err
}

// List takes label and field selectors, and returns the list of VirtletImageMappings that match those selectors.
func (c *FakeVirtletImageMappings) List(opts v1.ListOptions) (result *virtlet_k8s_v1.VirtletImageMappingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(virtletimagemappingsResource, virtletimagemappingsKind, c.ns, opts), &virtlet_k8s_v1.VirtletImageMappingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &virtlet_k8s_v1.VirtletImageMappingList{}
	for _, item := range obj.(*virtlet_k8s_v1.VirtletImageMappingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested virtletImageMappings.
func (c *FakeVirtletImageMappings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(virtletimagemappingsResource, c.ns, opts))

}

// Create takes the representation of a virtletImageMapping and creates it.  Returns the server's representation of the virtletImageMapping, and an error, if there is any.
func (c *FakeVirtletImageMappings) Create(virtletImageMapping *virtlet_k8s_v1.VirtletImageMapping) (result *virtlet_k8s_v1.VirtletImageMapping, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(virtletimagemappingsResource, c.ns, virtletImageMapping), &virtlet_k8s_v1.VirtletImageMapping{})

	if obj == nil {
		return nil, err
	}
	return obj.(*virtlet_k8s_v1.VirtletImageMapping), err
}

// Update takes the representation of a virtletImageMapping and updates it. Returns the server's representation of the virtletImageMapping, and an error, if there is any.
func (c *FakeVirtletImageMappings) Update(virtletImageMapping *virtlet_k8s_v1.VirtletImageMapping) (result *virtlet_k8s_v1.VirtletImageMapping, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(virtletimagemappingsResource, c.ns, virtletImageMapping), &virtlet_k8s_v1.VirtletImageMapping{})

	if obj == nil {
		return nil, err
	}
	return obj.(*virtlet_k8s_v1.VirtletImageMapping), err
}

// Delete takes name of the virtletImageMapping and deletes it. Returns an error if one occurs.
func (c *FakeVirtletImageMappings) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(virtletimagemappingsResource, c.ns, name), &virtlet_k8s_v1.VirtletImageMapping{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtletImageMappings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(virtletimagemappingsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &virtlet_k8s_v1.VirtletImageMappingList{})
	return err
}

// Patch applies the patch and returns the patched virtletImageMapping.
func (c *FakeVirtletImageMappings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *virtlet_k8s_v1.VirtletImageMapping, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(virtletimagemappingsResource, c.ns, name, data, subresources...), &virtlet_k8s_v1.VirtletImageMapping{})

	if obj == nil {
		return nil, err
	}
	return obj.(*virtlet_k8s_v1.VirtletImageMapping), err
}
