/*
Copyright 2018 Mirantis

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	virtlet_k8s_v1 "github.com/Mirantis/virtlet/pkg/api/virtlet.k8s/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVirtletConfigMappings implements VirtletConfigMappingInterface
type FakeVirtletConfigMappings struct {
	Fake *FakeVirtletV1
	ns   string
}

var virtletconfigmappingsResource = schema.GroupVersionResource{Group: "virtlet.k8s", Version: "v1", Resource: "virtletconfigmappings"}

var virtletconfigmappingsKind = schema.GroupVersionKind{Group: "virtlet.k8s", Version: "v1", Kind: "VirtletConfigMapping"}

// Get takes name of the virtletConfigMapping, and returns the corresponding virtletConfigMapping object, and an error if there is any.
func (c *FakeVirtletConfigMappings) Get(name string, options v1.GetOptions) (result *virtlet_k8s_v1.VirtletConfigMapping, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(virtletconfigmappingsResource, c.ns, name), &virtlet_k8s_v1.VirtletConfigMapping{})

	if obj == nil {
		return nil, err
	}
	return obj.(*virtlet_k8s_v1.VirtletConfigMapping), err
}

// List takes label and field selectors, and returns the list of VirtletConfigMappings that match those selectors.
func (c *FakeVirtletConfigMappings) List(opts v1.ListOptions) (result *virtlet_k8s_v1.VirtletConfigMappingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(virtletconfigmappingsResource, virtletconfigmappingsKind, c.ns, opts), &virtlet_k8s_v1.VirtletConfigMappingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &virtlet_k8s_v1.VirtletConfigMappingList{}
	for _, item := range obj.(*virtlet_k8s_v1.VirtletConfigMappingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested virtletConfigMappings.
func (c *FakeVirtletConfigMappings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(virtletconfigmappingsResource, c.ns, opts))

}

// Create takes the representation of a virtletConfigMapping and creates it.  Returns the server's representation of the virtletConfigMapping, and an error, if there is any.
func (c *FakeVirtletConfigMappings) Create(virtletConfigMapping *virtlet_k8s_v1.VirtletConfigMapping) (result *virtlet_k8s_v1.VirtletConfigMapping, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(virtletconfigmappingsResource, c.ns, virtletConfigMapping), &virtlet_k8s_v1.VirtletConfigMapping{})

	if obj == nil {
		return nil, err
	}
	return obj.(*virtlet_k8s_v1.VirtletConfigMapping), err
}

// Update takes the representation of a virtletConfigMapping and updates it. Returns the server's representation of the virtletConfigMapping, and an error, if there is any.
func (c *FakeVirtletConfigMappings) Update(virtletConfigMapping *virtlet_k8s_v1.VirtletConfigMapping) (result *virtlet_k8s_v1.VirtletConfigMapping, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(virtletconfigmappingsResource, c.ns, virtletConfigMapping), &virtlet_k8s_v1.VirtletConfigMapping{})

	if obj == nil {
		return nil, err
	}
	return obj.(*virtlet_k8s_v1.VirtletConfigMapping), err
}

// Delete takes name of the virtletConfigMapping and deletes it. Returns an error if one occurs.
func (c *FakeVirtletConfigMappings) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(virtletconfigmappingsResource, c.ns, name), &virtlet_k8s_v1.VirtletConfigMapping{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtletConfigMappings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(virtletconfigmappingsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &virtlet_k8s_v1.VirtletConfigMappingList{})
	return err
}

// Patch applies the patch and returns the patched virtletConfigMapping.
func (c *FakeVirtletConfigMappings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *virtlet_k8s_v1.VirtletConfigMapping, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(virtletconfigmappingsResource, c.ns, name, data, subresources...), &virtlet_k8s_v1.VirtletConfigMapping{})

	if obj == nil {
		return nil, err
	}
	return obj.(*virtlet_k8s_v1.VirtletConfigMapping), err
}
