- in:
    config:
      image:
        image: testImage
      labels:
        fizz: buzz
        foo: bar
      metadata:
        name: testcontainer
    pod_sandbox_id: 69eec606-0493-5825-73a4-c5e0c0236155
    sandbox_config:
      annotations:
        hello: world
        virt: let
      hostname: localhost
      labels:
        fizz: buzz
        foo: bar
      linux:
        security_context:
          namespace_options: {}
      log_directory: /var/log/test_log_directory
      metadata:
        name: testName_0
        namespace: default
        uid: 69eec606-0493-5825-73a4-c5e0c0236155
  out:
    Attempt: 0
    CPUPeriod: 0
    CPUQuota: 0
    CPUShares: 0
    ContainerAnnotations: null
    ContainerLabels:
      fizz: buzz
      foo: bar
    ContainerSideNetwork:
      Interfaces: null
      NsPath: /var/run/netns/bae464f1-6ee7-4ee2-826e-33293a9de95e
      Result: null
    DomainUUID: ""
    Environment: null
    Image: testImage
    LogDirectory: /var/log/test_log_directory
    LogPath: testcontainer_0.log
    MemoryLimitInBytes: 0
    Mounts: null
    Name: testcontainer
    ParsedAnnotations: null
    PodAnnotations:
      hello: world
      virt: let
    PodName: testName_0
    PodNamespace: default
    PodSandboxID: 69eec606-0493-5825-73a4-c5e0c0236155
    VolumeDevices: null
- in:
    config:
      image:
        image: testImage
      labels:
        fizz: buzz
        foo: bar
      log_path: some_logpath_0.log
      metadata:
        name: testcontainer
    pod_sandbox_id: 69eec606-0493-5825-73a4-c5e0c0236155
    sandbox_config:
      annotations:
        hello: world
        virt: let
      hostname: localhost
      labels:
        fizz: buzz
        foo: bar
      linux:
        security_context:
          namespace_options: {}
      log_directory: /some/pod/log/dir/69eec606-0493-5825-73a4-c5e0c0236155
      metadata:
        name: testName_0
        namespace: default
        uid: 69eec606-0493-5825-73a4-c5e0c0236155
  out:
    Attempt: 0
    CPUPeriod: 0
    CPUQuota: 0
    CPUShares: 0
    ContainerAnnotations: null
    ContainerLabels:
      fizz: buzz
      foo: bar
    ContainerSideNetwork:
      Interfaces: null
      NsPath: /var/run/netns/bae464f1-6ee7-4ee2-826e-33293a9de95e
      Result: null
    DomainUUID: ""
    Environment: null
    Image: testImage
    LogDirectory: /some/pod/log/dir/69eec606-0493-5825-73a4-c5e0c0236155
    LogPath: some_logpath_0.log
    MemoryLimitInBytes: 0
    Mounts: null
    Name: testcontainer
    ParsedAnnotations: null
    PodAnnotations:
      hello: world
      virt: let
    PodName: testName_0
    PodNamespace: default
    PodSandboxID: 69eec606-0493-5825-73a4-c5e0c0236155
    VolumeDevices: null
- in:
    config:
      image:
        image: testImage
      labels:
        fizz: buzz
        foo: bar
      metadata:
        name: testcontainer
      mounts:
      - container_path: /mnt
        host_path: /whatever
    pod_sandbox_id: d25ded14-d35d-510b-5749-f83cc165794e
    sandbox_config:
      annotations:
        hello: world
        virt: let
      hostname: localhost
      labels:
        fizz: buzz
        foo: bar
      linux:
        security_context:
          namespace_options: {}
      log_directory: /var/log/test_log_directory
      metadata:
        name: testName_1
        namespace: default
        uid: d25ded14-d35d-510b-5749-f83cc165794e
  out:
    Attempt: 0
    CPUPeriod: 0
    CPUQuota: 0
    CPUShares: 0
    ContainerAnnotations: null
    ContainerLabels:
      fizz: buzz
      foo: bar
    ContainerSideNetwork:
      Interfaces: null
      NsPath: /var/run/netns/bae464f1-6ee7-4ee2-826e-33293a9de95e
      Result: null
    DomainUUID: ""
    Environment: null
    Image: testImage
    LogDirectory: /var/log/test_log_directory
    LogPath: testcontainer_0.log
    MemoryLimitInBytes: 0
    Mounts:
    - ContainerPath: /mnt
      HostPath: /whatever
      Readonly: false
    Name: testcontainer
    ParsedAnnotations: null
    PodAnnotations:
      hello: world
      virt: let
    PodName: testName_1
    PodNamespace: default
    PodSandboxID: d25ded14-d35d-510b-5749-f83cc165794e
    VolumeDevices: null
