network-config:
  links:
  - ethernet_mac_address: "00:11:22:33:44:55"
    id: cni0
    mtu: 1500
    type: phy
  - ethernet_mac_address: 00:11:22:33:ab:cd
    id: cni1
    mtu: 1500
    type: phy
  networks:
  - id: net-0
    ip_address: 1.1.1.1
    link: cni0
    netmask: 255.0.0.0
    network_id: net-0
    routes:
    - gateway: 1.2.3.4
      netmask: 0.0.0.0
      network: 0.0.0.0
    type: ipv4
  - id: net-1
    ip_address: 192.168.100.42
    link: cni1
    netmask: 255.255.255.0
    network_id: net-1
    type: ipv4
  services:
  - address:
    - 1.2.3.4
    search:
    - some
    - search
    type: nameserver
